lr1_oauth/urls.py
from django.conf.urls import url
from lr1_oauth.views import IndexView, SuccessView, get_tweet, ErrorView, manual_start, manual_complete

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^success/', SuccessView.as_view(), name='success'),
    url(r'^error/', ErrorView.as_view(), name='error'),
    url(r'^get_tweet/(?P<backend>[^/]+)/$', get_tweet, name='get_tweet'),

    url(r'^manual/', manual_start, name='manual'),
    url(r'^complete/', manual_complete, name='complete')
]

lr2_api/urls.py
from django.conf.urls import url

from lr2_api.views import LocationsView, TravelCompaniesView, \
    PersonalInfoView, MyRoutesView, RouteView, RouteLocationView, RouteRegisterView, \
    AuthorizeView, AccessTokenView, RegisterView, LoginView, LogoutView

urlpatterns = [
    # fakes
    url(r'^register/', RegisterView.as_view(), name='usual_register'),
    url(r'^login/', LoginView.as_view(), name='usual_login'),
    url(r'^logout/', LogoutView.as_view(), name='usual_logout'),

    # auth
    url(r'^authorize/$', AuthorizeView.as_view(), name='authorize'),
    url(r'^token/$', AccessTokenView.as_view(), name='access_token'),

    # public
    url(r'^locations/$', LocationsView.as_view(), name='locations'),
    url(r'^companies/$', TravelCompaniesView.as_view(), name='travel_companies'),

    # by token
    url(r'^me/$', PersonalInfoView.as_view(), name='me'),
    url(r'^routes/$', MyRoutesView.as_view(), name='my_routes'),
    url(r'^route/$', RouteView.as_view(), name='route'),
    url(r'^route/(?P<route_id>\d+)/$', RouteView.as_view(), name='route'),

    url(r'^route/(?P<route_id>\d+)/location/(?P<location_id>\d+)/$',
        RouteLocationView.as_view(),
        name='route_location'),

    url(r'^route/(?P<route_id>\d+)/register/',
        RouteRegisterView.as_view(),
        name='register')
]

rsoi_labs/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^social/', include('social.apps.django_app.urls', namespace='social')),

    url(r'^oauth/', include('lr1_oauth.urls', namespace='oauth')),
    url(r'^api/', include('lr2_api.urls', namespace='api')),
    url(r'^o2p/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

lr1_oauth/views.py
import string
import requests
from urllib.parse import urlencode

from django.utils.crypto import get_random_string
from django.http import JsonResponse, HttpResponseRedirect, HttpResponseNotFound, HttpResponseBadRequest
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.auth import login

from social.apps.django_app.default.models import UserSocialAuth
from social.utils import setting_name
from social.apps.django_app.utils import psa

from lr1_oauth.utils import parse_qs, OAuth1

NAMESPACE = getattr(settings, setting_name('URL_NAMESPACE'), None) or 'social'


class IndexView(TemplateView):
    http_method_names = ['get']
    template_name = 'lr1_oauth/index.html'


class SuccessView(TemplateView):
    http_method_names = ['get']
    template_name = 'lr1_oauth/success.html'


class ErrorView(TemplateView):
    http_method_names = ['get']
    template_name = 'lr1_oauth/error.html'

    errors = {
        'denied': 'пользователь не хочет давать права',
        'user_refused': 'твиттер не подтвердил пользователя',
        'user_not_active': 'пользователь не активен'
    }
    def_error = 'неизвестная ошибка'

    def get_context_data(self, **kwargs):
        context = super(ErrorView, self).get_context_data(**kwargs)
        oauth_error = self.request.session.pop('oauth_error')
        context['err_msg'] = self.errors.get(oauth_error, self.def_error)
        return context


@psa('{0}:complete'.format(NAMESPACE))
def get_tweet(request, backend):
    backend = request.backend
    social = UserSocialAuth.objects.filter(user_id=request.user.id).first()
    if social:
        tweet = backend.get_json(
            'https://api.twitter.com/1.1/statuses/show.json',
            params={'id': '784737275766681600'},
            auth=backend.oauth_auth(social.access_token)
        )
    return JsonResponse(tweet)


def manual_start(request):
    key = settings.SOCIAL_AUTH_TWITTER_KEY
    secret = settings.SOCIAL_AUTH_TWITTER_SECRET
    state = get_random_string(32, string.ascii_letters + string.digits)
    request.session['state'] = state

    req_token_url = 'https://api.twitter.com/oauth/request_token'
    req_token_method = 'POST'
    redirect_uri = 'http://rsoi.local/oauth/complete/?redirect_state={}'.format(state)
    auth = OAuth1(key, secret, callback_uri=redirect_uri)

    response = requests.request(req_token_method, req_token_url, headers={}, params={}, auth=auth, timeout=None)
    response.raise_for_status()
    content = response.content

    token = content.decode(response.encoding)
    request.session['token'] = token
    token_data = parse_qs(token)

    print('\nПервый запрос\n', token_data)

    params = {
        'oauth_token': token_data.get('oauth_token'),
        'redirect_uri': redirect_uri
    }
    auth_url = 'https://api.twitter.com/oauth/authenticate'
    auth_url = '{0}?{1}'.format(auth_url, urlencode(params))
    return HttpResponseRedirect(redirect_to=auth_url)


def manual_complete(request):
    data = request.GET

    print('\nПосле редиректа\n', data)

    if 'denied' in data:
        request.session['oauth_error'] = 'denied'
        return HttpResponseRedirect('/oauth/error/')

    if 'oauth_problem' in data:
        request.session['oauth_error'] = data['oauth_problem']
        return HttpResponseRedirect('/oauth/error/')

    state = request.session.get('state')
    token = request.session.get('token')
    if not state or not token:
        return HttpResponseNotFound()

    req_state = data.get('redirect_state')
    req_token = data.get('oauth_token')
    if not req_state or not state == req_state:
        return HttpResponseBadRequest()

    token_data = parse_qs(token)
    if not token_data.get('oauth_token') == req_token:
        return HttpResponseBadRequest()

    key = settings.SOCIAL_AUTH_TWITTER_KEY
    secret = settings.SOCIAL_AUTH_TWITTER_SECRET
    oauth_verifier = data.get('oauth_verifier')

    resource_owner_key = token_data.get('oauth_token')
    resource_owner_secret = token_data.get('oauth_token_secret')
    if not resource_owner_key or not resource_owner_secret:
        return HttpResponseNotFound()

    redirect_uri = 'http://rsoi.local/oauth/complete/?redirect_state={}'.format(state)
    auth = OAuth1(key, secret, resource_owner_key=resource_owner_key, resource_owner_secret=resource_owner_secret,
                  callback_uri=redirect_uri, verifier=oauth_verifier)

    access_method = 'POST'
    access_url = 'https://api.twitter.com/oauth/access_token'
    response = requests.request(access_method, access_url, auth=auth)
    response.raise_for_status()
    access_token = parse_qs(response.text)

    print('\nAccess token\n', access_token)

    resource_owner_key = access_token.get('oauth_token')
    resource_owner_secret = access_token.get('oauth_token_secret')
    if not resource_owner_key or not resource_owner_secret:
        return HttpResponseNotFound()

    user_method = 'GET'
    user_url = 'https://api.twitter.com/1.1/account/verify_credentials.json'
    params = {'include_email': 'true'}
    auth = OAuth1(key, secret, resource_owner_key=resource_owner_key, resource_owner_secret=resource_owner_secret,
                  callback_uri=redirect_uri)

    response = requests.request(user_method, user_url, params=params, auth=auth)
    response.raise_for_status()

    data = response.json()
    if data and 'access_token' not in data:
        data['access_token'] = access_token

    print('\nДанные пользователя\n', data)

    user = request.user
    is_authenticated = user.is_authenticated()
    if is_authenticated:
        return HttpResponseRedirect(redirect_to='/oauth/success/')

    user_social = UserSocialAuth.objects.filter(uid=data.get('id')).first()
    if user_social:
        user = user_social.user
    else:
        request.session['oauth_error'] = 'user_not_active'
        return HttpResponseRedirect(redirect_to='/oauth/error/')

    if user.is_active:
        user.__dict__['backend'] = 'social.backends.twitter.TwitterOAuth'
        login(request, user)
        return HttpResponseRedirect(redirect_to='/oauth/success/')
    else:
        request.session['oauth_error'] = 'user_not_active'
        return HttpResponseRedirect(redirect_to='/oauth/error/')

lr1_oauth/templates/lr1_oauth/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}LR1 Oauth{% endblock %}</title>

    {% block css %}{% endblock %}
    {% block js %}{% endblock %}
</head>
<body>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

lr1_oauth/templates/lr1_oauth/error.html
{% extends 'lr1_oauth/base.html' %}
{% load static %}

{% block js %}
    <script src="{% static 'libs/jquery-3.1.1.min.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="error">
        <h3>Не удалось авторизоваться</h3>
        <h3>Детали: {{ err_msg }}</h3>
    </div>
{% endblock %}

lr1_oauth/templates/lr1_oauth/index.html
{% extends 'lr1_oauth/base.html' %}

{% block content %}
    <div class="auth">
        <h3>Авторизоваться через Twitter (OAuth 1a)</h3>
        <div class="auth__btn">
            <a href="{% url 'social:begin' backend='twitter' %}">Старт</a>
        </div>
        <hr>
        <div class="manual__btn">
            <a href="{% url 'oauth:manual' %}">Вручную</a>
        </div>
    </div>
{% endblock %}

lr1_oauth/templates/lr1_oauth/success.html
{% extends 'lr1_oauth/base.html' %}
{% load static %}

{% block js %}
    <script src="{% static 'libs/jquery-3.1.1.min.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="success">
        <h3>Вы успешно зарегистрированы</h3>
        {% with user=request.user %}
            <ul>
                <li><b>Имя</b>: {{ user.first_name }}</li>
                <li><b>Фамилия</b>: {{ user.last_name }}</li>
                <li><b>Email</b>: {{ user.email }}</li>
                <li><b>Nick</b>: {{ user.username }}</li>
                <li><b>Дата регистрации</b>: {{ user.date_joined }}</li>
                <li><b>Последний вход</b>: {{ user.last_login }}</li>
            </ul>
        {% endwith %}
        <a id="js-tweet" href="{% url 'oauth:get_tweet' backend='twitter' %}">Tweet</a>
        <br>
        <span id="tweet"></span>
    </div>
    <script>
        $('#js-tweet').click(function (event) {
            event.preventDefault();
            var url = $(this).attr('href');
            $.get(url).done(function (response) {
                $('#tweet').html(JSON.stringify(response));
            }).fail(function (xhr, textStatus) {
                console.log('error');
            });
        });
    </script>
{% endblock %}